name: Brad C. Hodson
favicon: null
layout_spectrum: 0.31301593221724033
typography_spectrum: 0.699253469472751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
